idf_component_register(
    SRCS
        "main.c"
        "rf.c"
        "rx5808.c"
    INCLUDE_DIRS "."
    REQUIRES
        esp_adc
        esp_driver_gpio
        esp_driver_parlio
        esp_driver_usb_serial_jtag
        esp_event
        esp_hw_support
        esp_mm
        esp_netif
        esp_rom
        esp_timer
        esp_wifi
        freertos
        hal
        nvs_flash
)
